### PR TITLE
Add example based on real London tube map

### PR DESCRIPTION
**Pull request by johnwalley**

### CODE REVIEW

**Comment by skamsie** [comment]
Thanks for creating this repo, the results look great! 

I would like to create a  project using your library to map the [ Berlin subway system](https://raw.githubusercontent.com/skamsie/berlin-subway/master/U-Bahn_Berlin.png) but I basically don't know where to start. I don't understand how you chose the coordinates for the stations? Is there a reasoning behind starting with Brixton at `"coords": [0, -20]` and not `[0, 0]` for example? Thank you in advance 🙇

**Comment by johnwalley** [comment]
Hi there,

Thanks for getting in touch.

It's very much a manual process, with lots of trial and error at
the moment. There's no real concept of an origin (0,0) so stations and
lines can be placed anywhere.

Looking at the U-Bahn, I think it should be possible to represent it. It
might be complicated in the section below.

[image: Screenshot 2019-12-11 at 21.44.29.png]

But we could possibly represent it like these stations in London which
share three lines.

[image: Screenshot 2019-12-11 at 21.47.25.png]

If you'd like to have a go at recreating a section of the U-Bahn (as small
as you like) I'd be happy to take a look and help out, and we can
hopefully extend it to the full map.

The London Underground is too complicated to reproduce whereas the map
you've linked looks like it would be possible!

John

**Comment by skamsie** [comment]
@johnwalley Thanks for replying... I have deleted my comment because I figured out in the meantime that it's pretty much trial and error. I have started working on it already, thank you for offering to help, I will let you know if I get stuck :)

**Comment by skamsie** [comment]
> Looking at the U-Bahn, I think it should be possible to represent it.

Hi, I though you might like this: https://github.com/skamsie/berlin-ubahn-map. I managed to replicate the Berlin U-Bahn system using a slightly modified version of your library. Thank you for creating this 👍 🙇

**Comment by johnwalley** [comment]
Wow, that looks amazing! Thanks for letting me know.

I've added a link to you in the README.

**Comment by skamsie** [comment]
Great, thanks!

**Pull request merged**
